# Generated by Django 4.2 on 2023-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject name')),
                ('prof', models.CharField(max_length=50, verbose_name='prof name')),
                ('startTime', models.TimeField(verbose_name='start time')),
                ('endTime', models.TimeField(verbose_name='end time')),
                ('classroom', models.CharField(max_length=50, verbose_name='classroom')),
            ],
        ),
    ]
