# Generated by Django 4.2 on 2023-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='weekday',
            field=models.CharField(default='hello', max_length=50, verbose_name='weekday'),
            preserve_default=False,
        ),
    ]
