# Generated by Django 4.2 on 2023-05-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_lecture_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lecture',
        ),
    ]
