# Generated by Django 4.2 on 2023-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='classroom',
            field=models.IntegerField(default=0, verbose_name='classroom'),
        ),
    ]
