# Generated by Django 4.2 on 2023-05-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_lecture_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='weekday',
            new_name='day',
        ),
    ]
